<?php
/**
 * WEB4PRO - Creating profitable online stores
 * 
 * @author WEB4PRO <srepin@corp.web4pro.com.ua>
 * @category  WEB4PRO
 * @package   Web4pro_Attachments
 * @copyright Copyright (c) 2015 WEB4PRO (http://www.web4pro.net)
 * @license   http://www.web4pro.net/license.txt
 */
/**
 * Attachment link widget template
 *
 * @category    Web4pro
 * @package     Web4pro_Attachments
 * @author      WEB4PRO <srepin@corp.web4pro.com.ua>
 */

/** @see Web4pro_Attachments_Block_Attachment_Widget_Link */
?>
<?php $_attachment = $this->getCurrentAttachment();?>
<?php if ($_attachment) :?>
    <div class="attachment-widget-link">
        <h2><?php echo $this->__('Attachments'); ?></h2>
        <?php echo $_attachment->getIcon(); ?>
        <?php $test =  $_attachment->getAttachmentUrl()?>
        <a href="<?php echo $_attachment->getAttachmentUrl()?>"><?php echo $_attachment->getTitle()?></a>
    </div>
<?php endif;?>
