<div class="contact-widget">
    <table>
        <tr>
            <td>Name</td>
            <td><?php echo $this->getData('name'); ?></td>
        </tr>
        <tr>
            <td>Address</td>
            <td><?php echo $this->getData('address'); ?></td>
        </tr>
        <tr>
            <td>Mobile</td>
            <td><?php echo $this->getData('mobile'); ?></td>
        </tr>
        <tr>
            <td>Website URL</td>
            <td><?php echo $this->getData('website'); ?></td>
        </tr>
    </table>
</div>