<div class="inup-socialconnect-register">
    <div class="<?php echo $this->_getColSet(); ?>">
        <?php if ($this->_weiboEnabled()): ?>
            <div class="<?php echo $this->_getCol(); ?> inup-socialconnect-register-weibo">
                <div class="fieldset">
                    <h2 class="legend"><?php echo $this->__('weibo Connect') ?></h2>
                    <p><?php echo $this->__('You can register using your weibo account.') ?></p>
                    <p><?php echo $this->getChildHtml('inup_socialconnect_checkout_weibo_button') ?></p>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($this->_qqEnabled()): ?>
            <div class="<?php echo $this->_getCol(); ?> inup-socialconnect-register-qq">
                <div class="fieldset">
                    <h2 class="legend"><?php echo $this->__('qq Connect') ?></h2>
                    <p><?php echo $this->__('You can register using your qq account.') ?></p>
                    <p><?php echo $this->getChildHtml('inup_socialconnect_checkout_qq_button') ?></p>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($this->_wechatEnabled()): ?>
            <div class="<?php echo $this->_getCol(); ?> inup-socialconnect-register-wechat">
                <div class="fieldset">
                    <h2 class="legend"><?php echo $this->__('Wechat Connect') ?></h2>
                    <p><?php echo $this->__('You can register using your Wechat account.') ?></p>
                    <p><?php echo $this->getChildHtml('inup_socialconnect_checkout_wechat_button') ?></p>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>